### ISSUE TITLE
Which Cam in NCLT

### ISSUE THREAD

**Issue by Song-Jingyu** [PoseNet-Mobile-Robot/Mobile-Robotics#8]
Hi,
I was trying to implement a pose estimation network and I wonder which cam (0-5) did you use in NCLT dataset? Thanks a lot!

**Comment by sahibdhanjal** [comment]
Hi Jingyu, we used the front left/ front right camera for training our model. I don't remember the cam ID since it was done a while back. Hopefully this should help you figure out what the cam IDs are.
